env: dev

replicas: 3

resources:
  cpuLimit: '6'
  memLimit: 18G
  cpuRequest: '3'
  memRequest: 14G
  xmx: 12G

subscriptions: subscriptions-dev.yml

configMap:
  projectId: carbon-1287
  gcsBucketName: anshar-dev
  ansharInboundUrl: https://api.dev.entur.io/realtime/v1/
  ansharEnvironment: test
  springProfile: gcs-blobstore
  concurrentPubsubConsumers: 10
  parallellPubsubMessagePulls: 1
  validationCount: 50
  validationSize: 25
  mqttEnabled: true
  hzBackupCount: 4

hpa:
  maxReplicas: 12
  minReplicas: 3
  targetCPUUtilizationPercentage: 80
