apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "app.name" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "common.labels" . | indent 4 }}
data:
    application.properties: |-
      server.port={{ .Values.service.http.internalPort }}

      spring.profiles.active={{ .Values.configMap.springProfile }}

      spring.cloud.gcp.project-id={{.Values.configMap.projectId}}
      spring.cloud.gcp.pubsub.project-id={{ .Values.configMap.projectId }}
      spring.cloud.gcp.pubsub.credentials.location=file://{{ .Values.secretMount.mountPath }}

      rutebanken.hazelcast.management.url=http://anshar-hzmgmt/hazelcast-mancenter/
      rutebanken.kubernetes.namespace={{ .Release.Namespace }}
      entur.hazelcast.backup.count.sync={{ .Values.configMap.hzBackupCount }}

      blobstore.gcs.project.id={{ .Values.configMap.projectId }}
      blobstore.gcs.container.name={{ .Values.configMap.gcsBucketName }}
      blobstore.gcs.credential.path={{ .Values.secretMount.mountPath }}

      anshar.environment={{ .Values.configMap.ansharEnvironment }}
      anshar.export.snapshot.cron.expression=0 0/10 0/1 ? * * *
      anshar.export.snapshot.tmpFolder=/deployments/export

      anshar.incoming.logdirectory=/deployments/incoming
      anshar.incoming.port={{ .Values.service.http.internalPort }}
      anshar.inbound.url={{ .Values.configMap.ansharInboundUrl }}
      anshar.outbound.polling.tracking.period.minutes=5

      anshar.outbound.pubsub.topic.enabled=true

      anshar.outbound.camel.route.topic.et.name=entur-google-pubsub://protobuf.estimated_timetables
      anshar.outbound.camel.route.topic.vm.name=entur-google-pubsub://protobuf.vehicle_monitoring
      anshar.outbound.camel.route.topic.sx.name=entur-google-pubsub://protobuf.situation_exchange

      anshar.mqtt.enabled={{ .Values.configMap.mqttEnabled }}
      anshar.mqtt.host=tcp://mqtt.default:1883

      anshar.default.max.elements.per.delivery=1000
      anshar.tracking.data.buffer.commit.frequency.seconds=15

      anshar.validation.data.persist.hours=240
      anshar.validation.total.max.count={{ .Values.configMap.validationCount }}
      anshar.validation.total.max.size.mb={{ .Values.configMap.validationSize }}

      anshar.message.queue.camel.route.prefix=entur-google-pubsub://
      anshar.incoming.concurrentConsumers={{ .Values.configMap.concurrentPubsubConsumers }}
      spring.cloud.gcp.pubsub.subscriber.parallel-pull-count=1
      spring.cloud.gcp.pubsub.subscriber.executor-threads=20

      anshar.bigdata.siri.et.export.camel.url=http4://big-daddy.default/siri/et

